tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      scan_logs: False
      force-branch: ceph-master
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
