overrides:
  ceph:
    cluster-conf:
      mgr:
        mgr/crash/warn_recent_interval: 0
    log-ignorelist:
      - Replacing daemon mds
      - \(MDS_INSUFFICIENT_STANDBY\)
      - \(MDS_ALL_DOWN\)
      - \(MDS_UP_LESS_THAN_MAX\)
      - \(MDS_DAMAGE\)
      - \(FS_DEGRADED\)
  ceph-fuse:
    disabled: true
tasks:
  - cephfs_test_runner:
      fail_on_skip: false
      modules:
        - tasks.cephfs.test_failover

