tasks:
- install:
- ceph:
- openssl_keys:
- rgw:
    client.0:

overrides:
  install:
    ceph:
      extra_system_packages:
        rpm:
        - luarocks
        deb:
        - luarocks
  ceph:
    conf:
      global:
        osd_min_pg_log_entries: 10
        osd_max_pg_log_entries: 10
      client:
        rgw lc debug interval: 10
