overrides:
  ceph:
    log-ignorelist:
    - \(POOL_APP_NOT_ENABLED\)
    conf:
      global:
        enable experimental unrecoverable data corrupting features: crimson
      mon:
        osd pool default crimson: true
      osd:
        crimson alien thread cpu cores: 9-11
        crimson osd obc lru size: 10
      osd.0:
        crimson seastar cpu cores: 0-2
      osd.1:
        crimson seastar cpu cores: 3-5
      osd.2:
        crimson seastar cpu cores: 6-8
    flavor: crimson
  workunit:
    env:
      CRIMSON_COMPAT: '1'
