overrides:
  check-counter:
    dry_run: true
  ceph:
    cluster-conf:
      mgr:
        mgr/crash/warn_recent_interval: 0
    log-ignorelist:
      - evicting unresponsive client
      - RECENT_CRASH

tasks:
- cephfs_test_runner:
    fail_on_skip: false
    modules:
      - tasks.cephfs.test_snapshots
