overrides:
  check-counter:
    counters:
      mds:
        - "mds.dir_split"
tasks:
- install:
    extra_system_packages:
      - bison
      - flex
      - elfutils-libelf-devel
      - openssl-devel
      - NetworkManager
      - iproute
      - util-linux
- workunit:
    clients:
      all:
        - kernel_untar_build.sh
